//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_GYM_CHINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO_THONGKE
    {
        public int MaBaoCao { get; set; }
        public Nullable<System.DateTime> NgayBaoCao { get; set; }
        public Nullable<int> TongSoThanhVien { get; set; }
        public Nullable<int> TongSoGoiTapDangKy { get; set; }
        public Nullable<int> TongSoBuoiTap { get; set; }
        public Nullable<decimal> TongDoanhThu { get; set; }
        public Nullable<int> SoLuongDichVu { get; set; }
        public Nullable<int> SoNhanVien { get; set; }
        public string GhiChu { get; set; }
    }
}
