//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_GYM_CHINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public int MaChamCong { get; set; }
        public int MaDKTV { get; set; }
        public System.DateTime NgayTap { get; set; }
    
        public virtual DK_THANHVIEN DK_THANHVIEN { get; set; }
    }
}
