//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_GYM_CHINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHONDICHVU
    {
        public int MaDichVu { get; set; }
        public Nullable<int> MaDangKy { get; set; }
        public string LoaiDichVu { get; set; }
        public string CoSo { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgayChon { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DANGKYGOI DANGKYGOI { get; set; }
    }
}
