//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_GYM_CHINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_DANGKYGOI
    {
        public int MaChiTiet { get; set; }
        public Nullable<int> MaDangKy { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoBuoi { get; set; }
        public Nullable<decimal> DonGia { get; set; }
    
        public virtual DANGKYGOI DANGKYGOI { get; set; }
    }
}
