//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_GYM_CHINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DK_THANHVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DK_THANHVIEN()
        {
            this.CHAMCONGs = new HashSet<CHAMCONG>();
        }
    
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public int MaGoiTap { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> SoBuoi { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string ThanhToan { get; set; }
        public int MaDKTV { get; set; }
    
        public virtual GOITAP GOITAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONG> CHAMCONGs { get; set; }
    }
}
