//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_GYM_CHINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GOITAP()
        {
            this.DANGKYGOIs = new HashSet<DANGKYGOI>();
        }
    
        public int MaGoiTap { get; set; }
        public string TenGoiTap { get; set; }
        public string ImageGoi { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> MaLoaiGoi { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANGKYGOI> DANGKYGOIs { get; set; }
        public virtual LOAIGOITAP LOAIGOITAP { get; set; }
    }
}
