//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_GYM_CHINH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHTAP
    {
        public int MaLichTap { get; set; }
        public int MaHLV { get; set; }
        public System.DateTime NgayTap { get; set; }
        public Nullable<System.TimeSpan> GioBatDau { get; set; }
        public Nullable<System.TimeSpan> GioKetThuc { get; set; }
        public string NoiDung { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
