//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_GYM_CHINH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBWebGymEntities : DbContext
    {
        public DBWebGymEntities()
            : base("name=DBWebGymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CHONDICHVU> CHONDICHVUs { get; set; }
        public virtual DbSet<CT_DANGKYGOI> CT_DANGKYGOI { get; set; }
        public virtual DbSet<DANGKYGOI> DANGKYGOIs { get; set; }
        public virtual DbSet<GOITAP> GOITAPs { get; set; }
        public virtual DbSet<LICHTAP> LICHTAPs { get; set; }
        public virtual DbSet<LOAIGOITAP> LOAIGOITAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHONGTAP> PHONGTAPs { get; set; }
        public virtual DbSet<THANHTOAN> THANHTOANs { get; set; }
        public virtual DbSet<THANHVIEN> THANHVIENs { get; set; }
        public virtual DbSet<DK_THANHVIEN> DK_THANHVIEN { get; set; }
        public virtual DbSet<BAOCAO_THONGKE> BAOCAO_THONGKE { get; set; }
        public virtual DbSet<CHAMCONG> CHAMCONGs { get; set; }
    }
}
